### PR TITLE
Fix GA/EA action

### PR DESCRIPTION
**Pull request by SentryMan**
Also add maven cache

### CODE REVIEW

**Comment by SentryMan** [comment]
Well I suppose it's only natural lombok would fail the EA build since they don't support a JDK until after it becomes GA

**Comment by ascopes** [comment]
We could update the Lombok example with a selector.groovy that filters out EA builds if you are able to determine that.

```groovy
// src/it/lombok/selector.groovy
if (thisIsAnEaBuild()) {
  println("Lombok is not supported in EA builds")
  return false
}

return true
```

that'd allow you to keep this enabled

**Comment by ascopes** [comment]
Yeah, thought that'd be a problem. Do you know if the JDK has any descriptor of the version being early access (e g. in the Runtime.version() API)?

**Comment by ascopes** [comment]
Wonder if it is worth checking that with a regex just to disable the specific tests that are problematic... what do you think? Is testing against EA likely to provide additional benefit do you think?

**Comment by SentryMan** [comment]
you can catch potential issues before they happen and notify the JDK devs before GA

**Comment by ascopes** [comment]
Might be worth adding then! I can take a look when I have some time unless you'd like to add it to this PR.

Thanks for fixing on such short notice, btw.

**Pull request merged**
